<a href="https://colab.research.google.com/github/kondapallimanohar/DataAnalysis/blob/main/DA_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#random module is sub-package of numpy

In [ ]:
A=np.random.rand(1)
print(A)

[0.19063009]


In [ ]:
#rand-range is between 0 and 1
A=np.random.rand(8,4)
print(A)

[[0.81345675 0.88384943 0.88896875 0.16168297]
 [0.78602543 0.06438239 0.84620175 0.22462862]
 [0.65588848 0.64912447 0.39083706 0.8714285 ]
 [0.67747369 0.28163232 0.6248355  0.89824843]
 [0.584288   0.04378866 0.25416714 0.00494327]
 [0.42313218 0.83884862 0.38731458 0.20008067]
 [0.63672263 0.00970782 0.61858871 0.09358142]
 [0.7196672  0.60082806 0.87386283 0.558745  ]]


In [ ]:
A=np.random.rand(4,8)
print(A)

[[0.64513922 0.20689168 0.06226554 0.79809219 0.32698393 0.79152823
  0.65250319 0.58563743]
 [0.15929697 0.01912624 0.17811818 0.77823989 0.90931922 0.23139484
  0.81210269 0.50997085]
 [0.47524239 0.3465699  0.95557428 0.70607425 0.9417624  0.84800835
  0.65547432 0.21283456]
 [0.31277686 0.37427873 0.5981096  0.28925923 0.36238443 0.09895544
  0.65837608 0.55658068]]


In [ ]:
A=np.floor(10*np.random.rand(8,4))
print(A) #rand-range

[[7. 0. 7. 8.]
 [9. 5. 4. 6.]
 [4. 5. 8. 2.]
 [6. 6. 3. 1.]
 [1. 5. 1. 6.]
 [6. 9. 3. 6.]
 [5. 6. 8. 2.]
 [3. 5. 8. 8.]]


In [ ]:
A=np.arange(1,33).reshape(8,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
print(np.vsplit(A,4))


[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24]]), array([[25, 26, 27, 28],
       [29, 30, 31, 32]])]


In [ ]:
print(np.vsplit(A,3))

ValueError: array split does not result in an equal division

In [ ]:
print(np.hsplit(A,4))

[array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21],
       [25],
       [29]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22],
       [26],
       [30]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23],
       [27],
       [31]]), array([[ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24],
       [28],
       [32]])]


In [ ]:
np.vsplit(A,(4,6))

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(A,(7,4))

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28]]),
 array([], shape=(0, 4), dtype=int64),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(A,(3,5))

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(A,(4,8))

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]),
 array([], shape=(0, 4), dtype=int64)]

In [ ]:
B=np.arange(32).reshape(4,8)
print(B)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [ ]:
np.hsplit(B,4)

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]]),
 array([[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29]]),
 array([[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31]])]

In [ ]:
np.hsplit(B,(3,7))

[array([[ 0,  1,  2],
        [ 8,  9, 10],
        [16, 17, 18],
        [24, 25, 26]]),
 array([[ 3,  4,  5,  6],
        [11, 12, 13, 14],
        [19, 20, 21, 22],
        [27, 28, 29, 30]]),
 array([[ 7],
        [15],
        [23],
        [31]])]

In [ ]:
np.hsplit(B,3)

ValueError: array split does not result in an equal division

In [ ]:
np.hsplit(B,(2,4))

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3,  4],
        [10, 11, 12],
        [18, 19, 20],
        [26, 27, 28]]),
 array([[ 5,  6,  7],
        [13, 14, 15],
        [21, 22, 23],
        [29, 30, 31]])]

Trigonometry

In [ ]:
np.pi

3.141592653589793

In [ ]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print("A=",A)

A= [0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
B=np.rad2deg(A)
print(B)

[ 45.  60.  90. 180.]


In [ ]:
np.rad2deg(1)

57.29577951308232

In [ ]:
np.deg2rad(180)

3.141592653589793

In [ ]:
np.deg2rad(1)

0.017453292519943295

In [ ]:
np.sin(A)

array([7.07106781e-01, 8.66025404e-01, 1.00000000e+00, 1.22464680e-16])

In [ ]:
np.sin(30)

-0.9880316240928618

In [ ]:
np.sin(1)

0.8414709848078965

In [ ]:
np.sin(1/2)

0.479425538604203

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

In [ ]:
np.tan(1/2)

0.5463024898437905

statistics

In [ ]:
st=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.std(st)

24.452334585202017

In [ ]:
np.var(st)

597.9166666666666

In [ ]:
c=np.arange(1,5).reshape(2,2)
print(c)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(c)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
c=np.arange(1,25).reshape(6,4)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
print(np.argmax(c))

23


In [ ]:
c=np.floor(10*np.random.rand(24)).reshape(6,4)
print(c)

[[0. 6. 3. 7.]
 [0. 0. 7. 8.]
 [7. 7. 7. 3.]
 [5. 5. 0. 5.]
 [1. 6. 5. 1.]
 [1. 8. 3. 5.]]


In [ ]:
np.argmax(c)

7

In [ ]:
c=10*np.random.rand(24).reshape(6,4)
print(c)

[[8.7421989  6.33378115 6.37240273 2.52204982]
 [7.53248487 1.7250437  6.67869653 6.48608238]
 [4.17870785 4.14708104 4.88028838 5.21139762]
 [7.26672374 4.89867505 3.75866845 3.78622987]
 [2.426598   9.08623911 0.0247504  7.75969129]
 [6.98064186 2.46400619 0.02922854 1.51432776]]


In [ ]:
np.argmax(c)

17

In [ ]:
print(np.argmax(c,axis=1))

[0 0 3 0 1 0]


In [ ]:
print(np.argmax(c,axis=0))

[0 4 1 4]


In [ ]:
print(np.argmin(c))

18


In [ ]:
print(np.argmin(c,axis=1))

[3 1 1 2 2 2]


In [ ]:
print(np.argmin(c,axis=0))

[4 1 4 5]


searching

In [ ]:
a=np.array([34,56,78,23,1,67,90])
print(np.where(a%2==0))

(array([0, 1, 2, 6]),)


In [ ]:
print(np.where(a%2!=0))

(array([3, 4, 5]),)


In [ ]:
ar=np.array([24,16,7,17,54,60])
print(np.where(ar%6==0))

(array([0, 4, 5]),)


In [ ]:
a=np.array([6,7,8,9,10])
x=np.searchsorted(a,10)
print(x)

4


In [ ]:
a=np.array([6,7,8,9,10])
x=np.searchsorted(a,10)
print(x)

4


In [ ]:
name=np.array(["manohar","revanth","hemanth"])
x=np.searchsorted(name,"hemanth")
print(np.sort(name))

['hemanth' 'manohar' 'revanth']


In [ ]:
name=np.array(["manohar","revanth","hemanth"])
print(np.where("manohar"))

(array([0]),)


In [ ]:
arr=np.array(["TRUE","FALSE","TRUE"])
print(np.sort(arr))

['FALSE' 'TRUE' 'TRUE']


In [ ]:
arr=np.array([[2,3,5],[6,7,8]])
print(np.sort(arr))

[[2 3 5]
 [6 7 8]]


In [ ]:
arr1=np.array([44,67,78]) #filtrs
x=[True,False,True]
newarr=arr1[x]
print(newarr)

[44 78]


In [ ]:
arr=np.array([45,21,55,48,24,15,85])
filt=np.where(arr%2==0)
print(filt)

(array([3, 4]),)


In [ ]:
arr[filt]

array([48, 24])

In [ ]:
arr[0],arr[1],arr[2],arr[3],arr[4],arr[5]

(45, 21, 55, 48, 24, 15)

iterating through arrays

In [ ]:
a=np.array(["abdul","revanth","manohar","hemanth"])
initials=np.array(["M","KO","KD","K"])
for i,j in zip(initials,a):
  print(i,">",j)

M > abdul
KO > revanth
KD > manohar
K > hemanth


In [ ]:
a1=([10,20,30,40,50])
a2=([11,22,33,44,55])
n=np.multiply(a1,a2)
print(n)

[ 110  440  990 1760 2750]


In [ ]:
a1=([10,20,30,40,50])
a2=([11,22,33,44,55])
n=np.divide(a1,a2)
print(n)

[0.90909091 0.90909091 0.90909091 0.90909091 0.90909091]


In [ ]:
a1=([10,20,30,40,50])
a2=([11,22,33,44,55])
n=np.mod(a1,a2)
print(n)

[10 20 30 40 50]


In [ ]:
a1=([10,20,30,40,50])
a2=([11,22,33,44,55])
n=np.divmod(a1,a2)
print(n)

(array([0, 0, 0, 0, 0]), array([10, 20, 30, 40, 50]))


In [ ]:
a1=([10,21,30,40,50,60])
a2=([20,12,2,20,25,25])
n=np.divide(a1,a2)
print(n)

[ 0.5   1.75 15.    2.    2.    2.4 ]


In [ ]:
a1=([10,21,30,40,50,60])
a2=([20,12,2,20,25,25])
n=np.mod(a1,a2)
print(n)

[10  9  0  0  0 10]


logarithms

In [ ]:
a1=np.arange(1,10)
print(a1)
print(np.log2(a1))

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [ ]:
a=1.2
print(np.log(a))

0.1823215567939546


In [ ]:
a=1.2
print(np.log2(a))

0.2630344058337938


In [ ]:
a=1.2
print(np.log10(a))

0.07918124604762482


other mathematical functions

In [ ]:
a2=np.array([5,6,100,50])
x=np.cumprod(a2)
print(x)

[     5     30   3000 150000]


In [ ]:
a1=np.array([10,15,25,15])
newarr=np.diff(a1)
print(newarr)

[  5  10 -10]


In [ ]:
num1=455
num2=665
x=np.lcm(num1,num2)
print(x)

8645


In [ ]:
num1=455
num2=665
x=np.gcd(num1,num2)
print(x)

35


In [ ]:
a1=np.array([10,15,25,15])
x=np.gcd.reduce(a1)
print(x)

5


In [ ]:
a1=np.array([10,15,25,15])
x=np.cumsum(a1)
print(x)

[10 25 50 65]


In [ ]:
a1=np.array([10,15,25,15])
x=np.lcm.reduce(a1)
print(x)

150
